services:
  server:
    build: ./server
    image: vixvify/movie-server
    container_name: movie-server
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "3001:3001"

  client:
    build: ./client
    image: vixvify/movie-client
    container_name: movie-client
    restart: always
    env_file:
      - ./client/.env
    depends_on:
      - server
    ports:
      - "3000:3000"
